[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "accident-detection-api"
version = "1.0.0"
description = "API for managing accident detection and prevention systems"
requires-python = ">=3.9" 