services:
  - type: web
    name: accident-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: accident-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    plan: free
    region: oregon
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1

databases:
  - name: accident-db
    databaseName: accident_detection
    user: accident_user
    plan: free
    ipAllowList: [] # only allow internal connections